spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "https://r.stripe.com"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PATCH
              - DELETE
            allowedHeaders:
              - "Access-Control-Allow-Origin"
              - "Content-Type"
              - "Authorization"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: "gateway-service"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    admin:
      auto-create: false
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true