spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Match all paths
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true