spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
              - "http://localhost:5176"
              - "http://localhost:5177"
              - "http://localhost:5178"
              - "http://localhost:5179"
              - "http://localhost:5180"
              - "https://admin.tail03350e.ts.net"
              - "https://end-user.tail03350e.ts.net"
              - "https://charitan.tail03350e.ts.net"
              - "https://r.stripe.com"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - OPTIONS
              - PATCH
              - DELETE
            allowed-headers:
              - "Access-Control-Allow-Origin"
              - "Content-Type"
              - "Authorization"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: "gateway-service"
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    admin:
      auto-create: false
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

