spring:
  application:
    name: "gateway"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: "admin-gateway-service"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true